### Pipeline ###
pipeline: 'engineering_pipeline'

### API Keys ###
openai_api_key: 'YOUR API KEY'


### OpenAI Default Configs ###
### All calls to OpenAI will use these configs unless otherwise specified in pipeline ###

default_model: 'gpt-4' # Recommended to set to a cheaper model for testing.
default_temperature: 0.8
default_max_tokens: Null
default_top_p: 1
default_frequency_penalty: 0
default_presence_penalty: 0

### Logging ###
wandb_enabled: false

working_codebase_dirname: 'generated_code' # A folder that exists 