### OpenAI Key
openai_api_key: 'YOUR_API_KEY_HERE'

### OpenAI Default Configs ###
### All calls to OpenAI will use these configs unless otherwise specified ###

default_model: 'gpt-4' # Recommended to set to a cheaper model for testing.
default_temperature: 1
default_max_tokens: Null
default_top_p: 1
default_frequency_penalty: 0
default_presence_penalty: 0

### Logging ###
wandb_enabled: false

### Pipeline ###
pipeline: 'task_pipeline'