### Pipeline ###
pipeline: 'advertising_pipeline'

### OpenAI Default Configs ###
### All calls to OpenAI will use these configs unless otherwise specified in pipeline ###

default_model: 'gpt-4' # Recommended to set to a cheaper model for testing.
default_temperature: 0.8
default_max_tokens: Null
default_top_p: 1
default_frequency_penalty: 0
default_presence_penalty: 0

### Logging ###
wandb_enabled: false

### Tools ### -- Early days, currently only an image generator tool.
# Current version of tools leads to decreased agent performance (uses up context), so is disabled by default.
tools_enabled: false


### Files to save outputs to generate_output folder ###
working_codebase_dirname: 'code' 
working_image_dirname: 'images' 