wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693396646.289288
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 19
      - 23
      4: 3.11.5
      5: 0.15.8
      8:
      - 4
      - 5
wandb_enabled:
  desc: null
  value: true
