pipeline: 
  - module: start_module
    inputs: []
    output_name: request
  - module: advertising_planner
    inputs: [request]
    output_name: advert_plan
  - module: slogan_generator
    model_config:
      model: 'gpt-4'
      temperature: 1.2
    inputs: [request, advert_plan]
    output_name: slogan
  - module: script_writer
    supplement: "This is for a TV spot, 30 seconds long."
    model_config:
      model: 'gpt-3.5-turbo'
      temperature: 1.2
    inputs: [request, advert_plan, slogan]
    output_name: script