pipeline: 
  - module: start_module
    inputs: []
    output_name: request
  - module: advertising_planner
    inputs: [request]
    output_name: advert_plan
  - module: slogan_generator
    model_config:
      model: 'gpt-4'
      temperature: 1.2
    inputs: [request, advert_plan]
    output_name: slogan
  - module: script_writer
    supplement: "TV spot, 30 seconds"
    inputs: [request, advert_plan, slogan]
    output_name: script
  - module: illustrator
    supplement: "Create the storyboard"
    inputs: [request, script]
    output_name: illustrations