pipeline: 
  - module: start_module
    inputs: []
    output_name: request
  - module: advertising_planner
    inputs: [request]
    supplement: "males 18-45"
    output_name: advert_plan
  - module: slogan_generator
    model_config:
      model: 'gpt-4'
      temperature: 1.2
    inputs: [request, advert_plan]
    output_name: slogan