pipeline: 
  - module: start_module
    inputs: []
    output_name: request
  - module: storyteller
    inputs: [request]
    output_name: story
  - module: illustrator
    inputs: [request, story]
    output_name: illustration